# Generated by Django 5.2.1 on 2025-05-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalexam', '0002_comment_created_at_product_slug_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
